### ISSUE TITLE
Is grid layout the best way of representing the search results?

### ISSUE THREAD

**Issue by ruiwanguk** [PRIDE-Cluster/cluster-design#1]
How about traditional table layout instead? This will probably allow better sorting and comparing different clusters.

**Comment by jadianes** [comment]
I don't necessarilly agree with tabular listing being better for sorting and comparing. It is more rigorous sorting, yes, but it depends on how rigorous is sorting in the results presented.

About comparing, I think a grid layout allows a more compact presentation of results and therefore allows comparing more results. Also, thanks to its better use of the space, the user needs to scroll less to find what she or he is looking for.

It all boils down to what do we want to achieve with the search results page. Are we looking for a strict ordering of the results (whether this makes sense to the user or not), or help findability of interesting results that will be later accessed in detail.

**Comment by jadianes** [comment]
Another thing to consider is how many results is the user going to consider. If we are talking about very few of them, typically the first 1-3 results, a grid results would be overkill despite its visual benefits and exploration possibilities. This is the typical Google search situation where the user more or less knows what is looking for (and sorting is not really needed).

If instead, the user is exploring and needs to consider many results, either because wants to see its search into the context of the search space or because its search term its not very specific, having more results in the visual space has its benefits for findability. In bot cases, tabular and grid, we should consider the uses of sorting and its possibilities in each of the layouts.

**Comment by ruiwanguk** [comment]
I totally agree with the user testing, actually I got this feedback from a user. :smile: My impression is that our users are so use to the traditional table format, where they can easily figure how to sort and compare the data. In the grid layout, it is kind of _new_ visual concept, they will need to get use to, hence the feedback. 

Another point worth considering is that, using the grid layout, if users choose to sort, we need to show them that how the results were sorted, is it left to right? or top to bottom? I feel that this might be tricky.

**Comment by ruiwanguk** [comment]
On the other hand, I completely understand and appreciate that in this project, we want to innovate and try out new ideas. 

:question: : I am wondering how much work is it to support both layouts? If it is not too much work, then we can support both, and do AB testing afterwards.

**Comment by jadianes** [comment]
Those are indeed the two main issues of not using a traditional tabular format: user habits and sorting explanation. The first one, is important, but being this a new resource, with not so many users, at least we should leave the door open to innovation. Actually a new way of presenting the information could improve the traditional one and create a new habit.

Explaining the sorting on a grid-based layout is tricky, true. However I wouldn't assume straight away it is counter intuitive. Three thoughts on this:

1) I think the first idea that comes to mind is that results are at least sorted top to bottom. Then left to right seems to be a cultural thing that we should not give for granted.
2) Context gives information on the sorting. That is, if you are applying a given sorting criteria, it should be obvious from the results that they are sorted top to bottom and left to right if the information in the results includes the sorting criteria (e.g. number of spectra). Hence, this should be self-explanatory.
3) How important is a super-precise tabular-like sorting for the search results? I already mentioned this, but I can't help to mention again because this concept is super important. We should really think about the purpose of the search result page. It is for presenting and **comparing** tabular data as we do in a spreadsheet? Is it a gateway for users **to find** what they are looking for? The first calls for a tabular layout. The second for something with more context and better visual attraction.

Finally, when I talk about user testing, I think more about user feedback based on product use. As we have learnt individual user comments are not always good feedback for two reasons. First they are just individual users, not always giving feedback on real usage. Second, what a user says is not always what she or he wants or is better for them :)

**Comment by jadianes** [comment]
Good point Rui! Supporting both layouts shouldn't be a lot of work. I think it would be great if we can have both, show one of them randomly, and get usage feedback! :)

**Comment by noedelta** [comment]
Hi. I was wondering the same, because both layout are useful for different reasons, maybe we can try to support both? I will look for angularJS projects and try to find something that we can reuse.

**Comment by ruiwanguk** [comment]
Ok, sounds like we have reached an agreement. I will close this issue if nobody says otherwise.

**Comment by ruiwanguk** [comment]
I will try to update the mockups just to reflect the conclusion.

**Comment by ypriverol** [comment]
Rui can you make public the mockups
